from typing import Protocol, List
from app.schemas import MetricsRecord

class MetricsStore(Protocol):
    def init(self) -> None: ...
    def save(self, record: MetricsRecord) -> None: ...
    def read_latest(self, limit: int = 100) -> List[MetricsRecord]: ...

